// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass Extensions : Windows.UI.Xaml.Controls.Page
    {
        Extensions();
        ExtensionsViewModel ViewModel { get; };
    }

    [default_interface] runtimeclass ExtensionsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        ExtensionsViewModel(Microsoft.Terminal.Settings.Model.CascadiaSettings settings);

        // Views
        Windows.Foundation.Collections.IVectorView<Microsoft.Terminal.Settings.Model.FragmentSettings> FragmentExtensions { get; };
        Windows.Foundation.Collections.IVectorView<Microsoft.Terminal.Settings.Model.Profile> ProfilesModified { get; };
        Windows.Foundation.Collections.IVectorView<Microsoft.Terminal.Settings.Model.Profile> ProfilesAdded { get; };
        Windows.Foundation.Collections.IVectorView<Microsoft.Terminal.Settings.Model.ColorScheme> ColorSchemesAdded { get; };

        // Methods
        Boolean GetExtensionState(String extensionSource);
        void SetExtensionState(String extensionSource, Boolean enableExt);
    }
}
